SUPABASE_URL = "https://qlzhfxxxgteuzvkqetin.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsemhmeHh4Z3RldXp2a3FldGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyMDk4MTAsImV4cCI6MjA4MTc4NTgxMH0.lRdvXohD6L6VXH0jG_VxWu9rkv0t3-c9wY_IH7oBTI8"
