SUPABASE_URL = "https://qlzhfxxxgteuzvkqetin.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsemhmeHh4Z3RldXp2a3FldGluIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjIwOTgxMCwiZXhwIjoyMDgxNzg1ODEwfQ.HVmVTS7SW3rbaBhrMdXHtX-UdOF-fDp_2tCfzSCWK80"
